#!/usr/bin/env node

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { fetchWithRetry } from "../src/_internals/fetch-with-retry/fetch-with-retry.ts";

const scriptsDir = import.meta.dirname;

const BACEN_CSV_URL =
	"https://www.bcb.gov.br/content/estabilidadefinanceira/str1/ParticipantesSTR.csv";

const BRASIL_API_URL = "https://brasilapi.com.br/api/banks/v1";

type BankRow = {
	code: string;
	ispb: string;
	name: string;
};

type BrasilApiBank = {
	ispb?: string;
	code?: number;
	name?: string;
	fullName?: string;
};

const isBrasilApiBank = (value: unknown): value is BrasilApiBank =>
	typeof value === "object" &&
	value !== null &&
	(!("ispb" in value) || typeof value.ispb === "string") &&
	(!("code" in value) || typeof value.code === "number") &&
	(!("name" in value) || typeof value.name === "string") &&
	(!("fullName" in value) || typeof value.fullName === "string");

const parseCsvLine = (line: string): string[] => {
	const fields: string[] = [];
	let current = "";
	let inQuotes = false;

	for (let i = 0; i < line.length; i++) {
		const char = line[i];

		if (inQuotes) {
			if (char === '"' && line[i + 1] === '"') {
				current += '"';
				i++;
			} else if (char === '"') {
				inQuotes = false;
			} else {
				current += char;
			}
		} else if (char === '"') {
			inQuotes = true;
		} else if (char === ",") {
			fields.push(current);
			current = "";
		} else {
			current += char;
		}
	}

	fields.push(current);

	return fields;
};

const fetchFromBacen = async (): Promise<BankRow[]> => {
	const response = await fetchWithRetry(BACEN_CSV_URL);

	if (!response.ok) {
		throw new Error(`Bacen STR participants request failed with status ${response.status}`);
	}

	const body = await response.text();
	const text = body.replace(/^\uFEFF/, "");
	const [, ...rows] = text.split(/\r\n|\n/).filter((line) => line.length > 0);

	const banks: BankRow[] = [];

	for (const row of rows) {
		const fields = parseCsvLine(row);
		const ispb = fields[0];
		const code = fields[2];
		const name = fields[5];

		if (
			ispb === undefined ||
			ispb === "" ||
			code === undefined ||
			code === "" ||
			name === undefined ||
			name === "" ||
			!/^\d{1,3}$/.test(code) ||
			Number(code) === 0
		) {
			continue;
		}

		banks.push({ code: code.padStart(3, "0"), ispb, name: name.trim() });
	}

	return banks;
};

const fetchFromBrasilApi = async (): Promise<BankRow[]> => {
	const response = await fetchWithRetry(BRASIL_API_URL);

	if (!response.ok) {
		throw new Error(`BrasilAPI banks request failed with status ${response.status}`);
	}

	const json: unknown = await response.json();

	if (!Array.isArray(json)) {
		throw new TypeError("BrasilAPI banks payload is not an array");
	}

	const banks: BankRow[] = [];

	for (const entry of json) {
		if (!isBrasilApiBank(entry) || typeof entry.code !== "number") continue;
		if (!Number.isInteger(entry.code) || entry.code < 0 || entry.code > 999) continue;

		const ispb = entry.ispb;

		if (ispb === undefined || ispb === "") continue;

		const name = (entry.fullName ?? entry.name ?? "").trim();

		if (name === "") continue;

		banks.push({ code: String(entry.code).padStart(3, "0"), ispb, name });
	}

	return banks;
};

const main = async (): Promise<void> => {
	let banks: BankRow[];
	let source: string;

	try {
		banks = await fetchFromBacen();
		source = BACEN_CSV_URL;
	} catch (error) {
		console.error(
			`Bacen STR participants request failed, falling back to BrasilAPI: ${error instanceof Error ? error.message : String(error)}`,
		);
		banks = await fetchFromBrasilApi();
		source = BRASIL_API_URL;
	}

	const uniqueBanks = new Map<string, BankRow>();

	for (const bank of banks) {
		uniqueBanks.set(bank.code, bank);
	}

	const sorted = [...uniqueBanks.values()].sort((bankA, bankB) =>
		bankA.code > bankB.code ? 1 : -1,
	);

	if (sorted.length === 0) {
		throw new Error("Refusing to write an empty bank dataset");
	}

	console.log(`Generated ${sorted.length} banks from ${source}`);

	await writeFile(
		resolve(scriptsDir, "..", "./src/_internals/constants/banks.ts"),
		`/**
 * Brazilian STR (Sistema de Transferência de Reservas) participants that have a compensation
 * code (commonly known as COMPE), published by Banco Central do Brasil. Generated by
 * \`scripts/banks.ts\`.
 * @see ${BACEN_CSV_URL}
 */
export type Bank = {
	/** Compensation code (COMPE), 3 digits, zero-padded. */
	code: string;
	/** Identificador do Sistema de Pagamentos Brasileiro (ISPB), 8 digits, zero-padded. */
	ispb: string;
	/** Institution name, as published by Banco Central do Brasil. */
	name: string;
};

export const BANKS: Bank[] = ${JSON.stringify(sorted)};`,
	);

	const compeCodes = sorted.map((bank) => bank.code).join("");
	const constantsPath = resolve(scriptsDir, "..", "./src/is-valid-bank-account/constants.ts");
	const constants = await readFile(constantsPath, "utf8");
	const literal = (compeCodes.match(/.{1,90}/g) ?? []).map((chunk) => `\t"${chunk}"`).join(" +\n");
	const updated = constants.replace(
		/export const COMPE_CODES =\n(?:\t"\d*" \+\n)*\t"\d*";/,
		`export const COMPE_CODES =\n${literal};`,
	);

	if (updated === constants) {
		throw new Error("COMPE_CODES literal not found in src/is-valid-bank-account/constants.ts");
	}

	await writeFile(constantsPath, updated);
	console.log(`Updated COMPE_CODES with ${sorted.length} codes`);
};

await main().catch((error) => {
	console.error(error instanceof Error ? error.message : error);
	process.exit(1);
});
