#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { fetchWithRetry } from "../src/_internals/fetch-with-retry/fetch-with-retry.ts";

const scriptsDir = dirname(fileURLToPath(import.meta.url));

type CboEntry = {
	cbo: string;
	descricao: string;
};

const main = async () => {
	const response = await fetchWithRetry(
		"https://raw.githubusercontent.com/lucaashoff/lista-cbo-json/main/cbos.json",
	);

	if (!response.ok) {
		throw new Error(`CBO mirror request failed with status ${response.status}`);
	}

	const json: CboEntry[] = await response.json();

	const data: Record<string, string> = {};

	for (const entry of json) {
		const code = /^\d{5}$/.test(entry.cbo) ? `0${entry.cbo}` : entry.cbo;

		if (!/^\d{6}$/.test(code)) continue;

		data[code] = entry.descricao;
	}

	const sorted: Record<string, string> = {};
	for (const code of Object.keys(data).sort()) {
		sorted[code] = data[code];
	}

	await writeFile(
		resolve(scriptsDir, "..", "./src/_internals/constants/cbo.ts"),
		`/**
 * CBO 2002 (Classificação Brasileira de Ocupações) titles, indexed by the raw 6 digit code.
 *
 * The MTE download at mtecbo.gov.br requires a browser session and cannot be fetched
 * programmatically, so this table is generated from a public community mirror of the
 * official table. Codes that are not purely numeric with 6 digits in the source (a small
 * number of law enforcement and military ranks and a few sub-occupation codes suffixed
 * with a letter) are normalized by left padding a 5 digit numeric code with a zero, or
 * dropped when a letter is present, since \`Cbo.code\` only accepts 6 digits.
 *
 * Generated by \`node ./scripts/cbo.ts\`. Do not edit by hand.
 *
 * @see https://raw.githubusercontent.com/lucaashoff/lista-cbo-json/main/cbos.json
 * @see http://www.mtecbo.gov.br/cbosite/pages/downloads.jsf
 */
export const CBO_TITLES: Record<string, string> = ${JSON.stringify(sorted)};
`,
	);
};

await main().catch((error) => {
	console.error(error instanceof Error ? error.message : error);
	process.exit(1);
});
