#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { fetchSortedRecord } from "../src/_internals/fetch-sorted-record/fetch-sorted-record.ts";

const scriptsDir = import.meta.dirname;

const EMBEDDED_ENTRY_REGEX = /\s+(\d)\.(\d{3})\s+-\s+/g;

/**
 * Some rows of the mirror glue the next code into the description, e.g.
 * `1305;"... energia elétrica 1.306 - Aquisição de serviço ..."`, which both corrupts the
 * `1305` description and drops `1306`. Splits such a row into one entry per code.
 * @param {string} code - The CFOP code the row started with.
 * @param {string} description - The row description, possibly containing embedded codes.
 * @returns {[string, string][]} One `[code, description]` entry per code found in the row.
 */
const splitEmbeddedEntries = (code: string, description: string): [string, string][] => {
	const entries: [string, string][] = [];
	let currentCode = code;
	let lastIndex = 0;

	for (const match of description.matchAll(EMBEDDED_ENTRY_REGEX)) {
		entries.push([
			currentCode,
			description.slice(lastIndex, match.index).replaceAll(/\s+/g, " ").trim(),
		]);
		currentCode = `${match[1]}${match[2]}`;
		lastIndex = match.index + match[0].length;
	}

	entries.push([currentCode, description.slice(lastIndex).replaceAll(/\s+/g, " ").trim()]);

	return entries;
};

const main = async (): Promise<void> => {
	const sorted = await fetchSortedRecord(
		"https://raw.githubusercontent.com/jansenfelipe/cfop/master/cfop.csv",
		"CFOP mirror",
		async (response) => {
			const csv = await response.text();

			const data: Record<string, string> = {};

			for (const line of csv.split("\n")) {
				const match = /^(\d{4});"(.*)"\s*$/.exec(line);

				if (!match) continue;

				const [, code, description] = match;

				if (code === undefined || description === undefined) continue;

				for (const [entryCode, entryDescription] of splitEmbeddedEntries(code, description)) {
					if (entryCode.endsWith("00")) continue;

					data[entryCode] = entryDescription;
				}
			}

			return data;
		},
	);

	await writeFile(
		resolve(scriptsDir, "..", "./src/_internals/constants/cfop.ts"),
		`/**
 * CFOP (Código Fiscal de Operações e Prestações) table, indexed by the 4 digit code.
 *
 * Group and subgroup headers (codes ending in "00", e.g. "1000", "1100") are section
 * titles from the official nomenclature rather than operable codes, so they are excluded.
 *
 * Generated by \`node ./scripts/cfop.ts\`. Do not edit by hand.
 *
 * @see https://raw.githubusercontent.com/jansenfelipe/cfop/master/cfop.csv
 * @see https://www.confaz.fazenda.gov.br/legislacao/ajustes/2001/AJ_007_01
 */
export const CFOP_TABLE: Record<string, string> = ${JSON.stringify(sorted)};
`,
	);
};

await main().catch((error) => {
	console.error(error instanceof Error ? error.message : error);
	process.exit(1);
});
