#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { fetchWithRetry } from "../src/_internals/fetch-with-retry/fetch-with-retry.ts";

const scriptsDir = dirname(fileURLToPath(import.meta.url));

const EMBEDDED_ENTRY_REGEX = /\s+(\d)\.(\d{3})\s+-\s+/g;

/**
 * Some rows of the mirror glue the next code into the description, e.g.
 * `1305;"... energia elétrica 1.306 - Aquisição de serviço ..."`, which both corrupts the
 * `1305` description and drops `1306`. Splits such a row into one entry per code.
 */
const splitEmbeddedEntries = (code: string, description: string): [string, string][] => {
	const entries: [string, string][] = [];
	let currentCode = code;
	let lastIndex = 0;

	for (const match of description.matchAll(EMBEDDED_ENTRY_REGEX)) {
		entries.push([
			currentCode,
			description.slice(lastIndex, match.index).replace(/\s+/g, " ").trim(),
		]);
		currentCode = `${match[1]}${match[2]}`;
		lastIndex = match.index + match[0].length;
	}

	entries.push([currentCode, description.slice(lastIndex).replace(/\s+/g, " ").trim()]);

	return entries;
};

const main = async () => {
	const response = await fetchWithRetry(
		"https://raw.githubusercontent.com/jansenfelipe/cfop/master/cfop.csv",
	);

	if (!response.ok) {
		throw new Error(`CFOP mirror request failed with status ${response.status}`);
	}

	const csv = await response.text();

	const data: Record<string, string> = {};

	for (const line of csv.split("\n")) {
		const match = line.match(/^(\d{4});"(.*)"\s*$/);

		if (!match) continue;

		const [, code, description] = match;

		for (const [entryCode, entryDescription] of splitEmbeddedEntries(code, description)) {
			if (entryCode.endsWith("00")) continue;

			data[entryCode] = entryDescription;
		}
	}

	const sorted: Record<string, string> = {};
	for (const code of Object.keys(data).sort()) {
		sorted[code] = data[code];
	}

	await writeFile(
		resolve(scriptsDir, "..", "./src/_internals/constants/cfop.ts"),
		`/**
 * CFOP (Código Fiscal de Operações e Prestações) table, indexed by the 4 digit code.
 *
 * Group and subgroup headers (codes ending in "00", e.g. "1000", "1100") are section
 * titles from the official nomenclature rather than operable codes, so they are excluded.
 *
 * Generated by \`node ./scripts/cfop.ts\`. Do not edit by hand.
 *
 * @see https://raw.githubusercontent.com/jansenfelipe/cfop/master/cfop.csv
 * @see https://www.confaz.fazenda.gov.br/legislacao/ajustes/2001/AJ_007_01
 */
export const CFOP_TABLE: Record<string, string> = ${JSON.stringify(sorted)};
`,
	);
};

await main().catch((error) => {
	console.error(error instanceof Error ? error.message : error);
	process.exit(1);
});
