#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { DATA as STATES } from "../src/_internals/constants/states.ts";
import { fetchWithRetry } from "../src/_internals/fetch-with-retry/fetch-with-retry.ts";

const scriptsDir = dirname(fileURLToPath(import.meta.url));

const STATE_CODES = STATES.map((state) => state.code);

type City = {
	id: number;
	nome: string;
	microrregiao: {
		id: number;
		nome: string;
		mesorregiao: {
			id: number;
			nome: string;
			UF: {
				id: number;
				sigla: string;
				nome: string;
				regiao: {
					id: number;
					sigla: string;
					nome: string;
				};
			};
		};
	} | null;
	"regiao-imediata": {
		id: number;
		nome: string;
		"regiao-intermediaria": {
			id: number;
			nome: string;
			UF: {
				id: number;
				sigla: string;
				nome: string;
			};
		};
	};
};

const main = async () => {
	const response = await fetchWithRetry(
		"https://servicodados.ibge.gov.br/api/v1/localidades/municipios",
	);

	if (!response.ok) {
		throw new Error(`IBGE municipalities request failed with status ${response.status}`);
	}

	const json: City[] = await response.json();

	const byState = json.reduce(
		(acc, city) => {
			const stateInitials =
				city?.microrregiao?.mesorregiao?.UF?.sigla ??
				city?.["regiao-imediata"]?.["regiao-intermediaria"]?.UF?.sigla;

			if (!stateInitials) return acc;

			if (!acc[stateInitials]) {
				acc[stateInitials] = [];
			}

			acc[stateInitials].push([city.nome, String(city.id)]);

			return acc;
		},
		{} as Record<string, [string, string][]>,
	);

	const sortedEntries = Object.entries(byState)
		.sort(([a], [b]) => a.localeCompare(b))
		.map(
			([state, tuples]) => [state, tuples.sort(([a], [b]) => a.localeCompare(b, "pt-BR"))] as const,
		);

	const body = sortedEntries
		.map(([state, tuples]) => {
			const rows = tuples.map(([name, code]) => `\t\t[${JSON.stringify(name)}, "${code}"],`);

			return `\t${state}: [\n${rows.join("\n")}\n\t],`;
		})
		.join("\n");

	const missingStates = STATE_CODES.filter((code) => !byState[code]);

	if (missingStates.length > 0) {
		throw new Error(`IBGE response is missing municipalities for: ${missingStates.join(", ")}`);
	}

	await writeFile(
		resolve(scriptsDir, "..", "./src/_internals/constants/cities.ts"),
		`import type { StateCode } from "./states";

/**
 * Brazilian municipalities by state, published by the IBGE. \`DATA\` holds, for each state, a
 * \`[name, ibgeCode]\` tuple per municipality, sorted by name with \`localeCompare\` in the
 * "pt-BR" locale. Generated by \`scripts/cities.ts\`.
 *
 * @see https://servicodados.ibge.gov.br/api/docs/localidades
 */
export type Municipality = {
	/** The 7-digit IBGE municipality code. */
	code: string;
	/** The municipality name. */
	name: string;
	/** The two-letter code of the state the municipality belongs to. */
	stateCode: StateCode;
};

export const DATA: Record<StateCode, readonly (readonly [string, string])[]> = {
${body}
};
`,
	);
};

await main().catch((error) => {
	console.error(error instanceof Error ? error.message : error);
	process.exit(1);
});
