#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { fetchWithRetry } from "../src/_internals/fetch-with-retry/fetch-with-retry.ts";

const scriptsDir = dirname(fileURLToPath(import.meta.url));

type CnaeSubclass = {
	id: string;
	descricao: string;
};

const main = async () => {
	const response = await fetchWithRetry("https://servicodados.ibge.gov.br/api/v2/cnae/subclasses");

	if (!response.ok) {
		throw new Error(`IBGE CNAE request failed with status ${response.status}`);
	}

	const json: CnaeSubclass[] = await response.json();

	const entries = json
		.filter((subclass) => /^\d{7}$/.test(subclass.id))
		.sort((subclassA, subclassB) => (subclassA.id > subclassB.id ? 1 : -1))
		.map((subclass) => [subclass.id, subclass.descricao] as const);

	const data: Record<string, string> = {};
	for (const [id, descricao] of entries) {
		data[id] = descricao;
	}

	await writeFile(
		resolve(scriptsDir, "..", "./src/_internals/constants/cnae.ts"),
		`/**
 * CNAE 2.3 (Classificação Nacional de Atividades Econômicas) subclasses, indexed by the
 * raw 7 digit code, mapping to the official subclass description.
 *
 * Generated by \`node ./scripts/cnae.ts\`. Do not edit by hand.
 *
 * @see https://servicodados.ibge.gov.br/api/v2/cnae/subclasses
 * @see https://concla.ibge.gov.br/classificacoes/por-tema/atividades-economicas/classificacao-nacional-de-atividades-economicas
 */
export const CNAE_SUBCLASSES: Record<string, string> = ${JSON.stringify(data)};
`,
	);
};

await main().catch((error) => {
	console.error(error instanceof Error ? error.message : error);
	process.exit(1);
});
