#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { fetchWithRetry } from "../src/_internals/fetch-with-retry/fetch-with-retry.ts";

const scriptsDir = import.meta.dirname;

type NcmEntry = {
	Codigo: string;
	Data_Fim: string;
};

type NcmResponse = {
	Nomenclaturas: NcmEntry[];
};

const isNcmEntry = (value: unknown): value is NcmEntry =>
	typeof value === "object" &&
	value !== null &&
	"Codigo" in value &&
	typeof value.Codigo === "string" &&
	"Data_Fim" in value &&
	typeof value.Data_Fim === "string";

const isNcmResponse = (value: unknown): value is NcmResponse =>
	typeof value === "object" &&
	value !== null &&
	"Nomenclaturas" in value &&
	Array.isArray(value.Nomenclaturas) &&
	value.Nomenclaturas.every((entry) => isNcmEntry(entry));

const main = async (): Promise<void> => {
	const response = await fetchWithRetry(
		"https://portalunico.siscomex.gov.br/classif/api/publico/nomenclatura/download/json?perfil=PUBLICO",
	);

	if (!response.ok) {
		throw new Error(`Siscomex NCM request failed with status ${response.status}`);
	}

	const json: unknown = await response.json();

	if (!isNcmResponse(json)) {
		throw new Error("Siscomex NCM payload is not a Nomenclaturas response");
	}

	const codes = json.Nomenclaturas.filter(
		(entry) => entry.Data_Fim === "31/12/9999" && /^[\d.]{10}$/.test(entry.Codigo),
	)
		.map((entry) => entry.Codigo.replaceAll(/\D/g, ""))
		.filter((code) => code.length === 8);

	const uniqueSortedCodes = [...new Set(codes)].sort();

	await writeFile(
		resolve(scriptsDir, "..", "./src/is-valid-ncm/constants.ts"),
		`/**
 * Currently valid NCM (Nomenclatura Comum do Mercosul) 8 digit codes, sorted ascending.
 *
 * Generated by \`node ./scripts/ncm.ts\`. Do not edit by hand.
 *
 * @see https://portalunico.siscomex.gov.br/classif/api/publico/nomenclatura/download/json
 */
export const NCM_CODES: readonly string[] = ${JSON.stringify(uniqueSortedCodes)};
`,
	);
};

await main().catch((error) => {
	console.error(error instanceof Error ? error.message : error);
	process.exit(1);
});
